# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wEmc3erterhhydUC0Ad6LQoB8Z4B1T3i
"""

def usuario(): #se define la función Usuario que esta compuesta por las líneas que siguen
    nombre = input("Por favor ingrese su nombre: ") #se crea una variable llamada "nombre" cuyo valor depende del valor insertado luego del texto impreso que se encuentra dentro de las comillas
    print(f"Hola, {nombre}! Encantado de conocerte.") #se imprime la frase #se utilizan comillas para mostrar que es texto.  #la f se añade para especificar que hay una variable para imprimir #la variable se pone en corchetas
    print() #una línea por motivos esteticos
    print(f"¿En qué te puedo ayudar, {nombre}?")
    input()

usuario() #ejecutar la funcion Usuario